# Generated by Django 4.0.1 on 2022-01-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ask',
            name='story_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='ask',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ask',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='ask',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ask',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='story_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='story_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='story_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='show',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
