# Generated by Django 4.0.1 on 2022-01-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_ask_by_ask_story_id_ask_text_ask_time_ask_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
